name: NodeCI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, lint, unit test and e2e tests
      run: |
        npm install
        npm install -g @angular/cli
      env:
        CI: true
    - name: testing lint, build, unit test
      run: |
        npm run lint
        npm run build
        npm run test -- --configuration=ci --no-watch --no-progress --code-coverage
        npm run webdriver-update
        npm run e2e -- --configuration=ci
